### ISSUE TITLE
Can't use plugin

### ISSUE THREAD

**Issue by yvecai** [podolsir/osmosis-simplifyways#1]
I added the following line in osmosis-plugins.conf:
de.vwistuttgart.openstreetmap.osmosis.simplifyways.SimplifyWaysPluginLoader

But the plugin won't load:

Jan 8, 2012 5:29:25 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Osmosis Version 0.39
Jan 8, 2012 5:29:26 PM org.openstreetmap.osmosis.core.Osmosis main
SEVERE: Execution aborted.
org.openstreetmap.osmosis.core.OsmosisRuntimeException: Unable to load plugin class (de.vwistuttgart.openstreetmap.osmosis.simplifyways.SimplifyWaysPluginLoader).
    at org.openstreetmap.osmosis.core.TaskRegistrar.loadPluginClass(TaskRegistrar.java:327)
    at org.openstreetmap.osmosis.core.TaskRegistrar.loadPlugin(TaskRegistrar.java:306)
    at org.openstreetmap.osmosis.core.TaskRegistrar.loadBuiltInPlugins(TaskRegistrar.java:123)
    at org.openstreetmap.osmosis.core.TaskRegistrar.initialize(TaskRegistrar.java:80)
    at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:81)
    at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:329)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:239)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
    at org.codehaus.classworlds.Launcher.main(Launcher.java:31)
Caused by: java.lang.ClassNotFoundException: de.vwistuttgart.openstreetmap.osmosis.simplifyways.SimplifyWaysPluginLoader
    at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:244)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:230)
    at org.openstreetmap.osmosis.core.TaskRegistrar.loadPluginClass(TaskRegistrar.java:325)
    ... 14 more

Yves

**Comment by podolsir** [comment]
Yves,

umm, which osmosis-plugins.conf do you mean? 

And in any case, it doesn't work that way with this plexus container thingy... The simplest way to get the plugin to load is to copy its jar (and the jts jar) into the $OSMOSIS_HOME/lib/default directory. Or you can place it somewhere else and add that directory or the jar paths to $OSMOSIS_HOME/conf/plexus.conf file. Just like the README states :)

Hope that helps (and ask me if I got anything wrong)
Igor

**Comment by yvecai** [comment]
After build, the osmosis-simplifyways-v0.39.1.jar contain the same content than jts-1.11.jar !!
The zip file is OK.

**Comment by podolsir** [comment]
OK, thanks for the bug report, I'll look into the build the next days.
