### ISSUE TITLE
Is the plugin ready for osmosis 0.40.1?

### ISSUE THREAD

**Issue by yvecai** [podolsir/osmosis-simplifyways#2]
/home/website/src/osmosis-0.40.1/bin/osmosis \
--read-xml ${PLANET_DIR}planet_nordic_processed.osm \
--simplify-ways epsilonMeters=50 \
--used-node \
--write-xml file=${PLANET_DIR}planet_nordic_processed-50m.osm

gives me the following error:
19 sept. 2012 16:52:02 org.openstreetmap.osmosis.core.Osmosis run
INFO: Osmosis Version 0.41-4-ge47c386
19 sept. 2012 16:52:02 org.openstreetmap.osmosis.core.Osmosis run
INFO: Preparing pipeline.
19 sept. 2012 16:52:02 org.openstreetmap.osmosis.core.Osmosis run
INFO: Launching pipeline execution.
19 sept. 2012 16:52:02 org.openstreetmap.osmosis.core.Osmosis run
INFO: Pipeline executing, waiting for completion.
19 sept. 2012 16:52:02 org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
GRAVE: Thread for task 1-read-xml failed
java.lang.AbstractMethodError: de.vwistuttgart.openstreetmap.osmosis.simplifyways.v0_6.WaySimplifier.initialize(Ljava/util/Map;)V
    at org.openstreetmap.osmosis.xml.v0_6.XmlReader.run(XmlReader.java:95)
    at java.lang.Thread.run(Thread.java:679)
19 sept. 2012 16:52:02 org.openstreetmap.osmosis.core.Osmosis main
GRAVE: Execution aborted.
org.openstreetmap.osmosis.core.OsmosisRuntimeException: One or more tasks failed.
    at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.waitForCompletion(Pipeline.java:146)
    at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:92)
    at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:329)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:239)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
    at org.codehaus.classworlds.Launcher.main(Launcher.java:47)

**Comment by mvexel** [comment]
I just tried it with 0.43 and got a similar message:

```
java.lang.AbstractMethodError: de.vwistuttgart.openstreetmap.osmosis.simplifyways.v0_6.WaySimplifier.initialize(Ljava/util/Map;)V
    at crosby.binary.osmosis.OsmosisReader.run(OsmosisReader.java:43)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by noblige** [comment]
I made a PR - https://github.com/podolsir/osmosis-simplifyways/pull/3

**Comment by solitone** [comment]
This is what I get with Osmosis Version 0.47:

$ osmosis --read-xml sauze_contours.osm --simplify-ways epsilonMeters=10 --wx sauze_contours_simpld.osm
Mar 07, 2019 1:39:13 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Osmosis Version 0.47
Mar 07, 2019 1:39:13 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Preparing pipeline.
Mar 07, 2019 1:39:13 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Launching pipeline execution.
Mar 07, 2019 1:39:13 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Pipeline executing, waiting for completion.
Mar 07, 2019 1:39:13 PM org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
SEVERE: Thread for task 1-read-xml failed
java.lang.AbstractMethodError: Receiver class de.vwistuttgart.openstreetmap.osmosis.simplifyways.v0_6.WaySimplifier does not define or inherit an implementation of the resolved method abstract close()V of interface java.lang.AutoCloseable.
	at org.openstreetmap.osmosis.xml.v0_6.XmlReader.run(XmlReader.java:107)
	at java.base/java.lang.Thread.run(Thread.java:834)

Mar 07, 2019 1:39:13 PM org.openstreetmap.osmosis.core.Osmosis main
SEVERE: Execution aborted.
org.openstreetmap.osmosis.core.OsmosisRuntimeException: One or more tasks failed.
	at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.waitForCompletion(Pipeline.java:146)
	at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:92)
	at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
